hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

feign:
  client:
    config:
      default:
        connectTimeout: 11111
        readTimeout: 22222

security:
  oauth2:
    resource:
      user-info-uri: http://gateway/uaa/users/current


spring:
  sleuth:
    sampler:
      probability: 1
